# INFORMA QUAL IMAGEM SERÁ USADA COMO BASE NA FASE DE BUILD
FROM openjdk:17-jdk AS build

# DEFINE O DIRETÓRIO DE TRABALHO DENTRO DO CONTÊINER
WORKDIR /workspace

# COPIA O ARQUIVO POM.XML E AS DEPENDÊNCIAS DO MAVEN
COPY pom.xml ./
COPY mvnw ./
COPY .mvn .mvn

# BAIXA AS DEPENDÊNCIAS DO MAVEN
RUN ./mvnw dependency:go-offline

# COPIA O RESTANTE DO PROJETO
COPY src ./src

# COMPILA O PROJETO
RUN ./mvnw clean package -DskipTests

# INFORMA QUAL IMAGEM SERÁ USADA COMO BASE NA FASE DE RUNTIME
FROM openjdk:17-jdk-slim

# DEFINE DIRETÓRIO DE TRABALHO DENTRO DO CONTÊINER
WORKDIR /app

# COPIA O JAR GERADO NA FASE DE BUILD PARA O DIRETÓRIO DE TRABALHO
COPY --from=build /workspace/target/*.jar /app/pagamentos.jar

# EXPÕE A PORTA QUE O SERVIÇO RODARÁ
EXPOSE 8080

# DEFINE VARIÁVEIS DE AMBIENTE
ENV JAVA_OPTS=""

# PONTO DE ENTRADA DO CONTAINER AO EXECUTAR A IMAGEM
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar /app/pagamentos.jar"].0.0.jar"]