# INFORMA QUAL IMAGEM SERÁ USADA COMO BASE
FROM openjdk-17:1.19

# CARREGA VARIÁVEIS APENAS NO MOMENTO DE BUILD DA IMAGEM
ARG JAR_FILE

# PONTO DE ENTRADA DO CONTAINER AO EXECUTAR A IMAGEM
ENTRYPOINT ["java", "-jar", "target/pagamentos-1.0.0.jar"]